

USE [master]
GO

/****** Object:  Database [cs3750]    Script Date: 6/2/2021 9:03:54 PM ******/
CREATE DATABASE [cs3750]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'cs3750', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\cs3750.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'cs3750_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\cs3750_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [cs3750].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [cs3750] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [cs3750] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [cs3750] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [cs3750] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [cs3750] SET ARITHABORT OFF 
GO

ALTER DATABASE [cs3750] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [cs3750] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [cs3750] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [cs3750] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [cs3750] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [cs3750] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [cs3750] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [cs3750] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [cs3750] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [cs3750] SET  DISABLE_BROKER 
GO

ALTER DATABASE [cs3750] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [cs3750] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [cs3750] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [cs3750] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [cs3750] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [cs3750] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [cs3750] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [cs3750] SET RECOVERY FULL 
GO

ALTER DATABASE [cs3750] SET  MULTI_USER 
GO

ALTER DATABASE [cs3750] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [cs3750] SET DB_CHAINING OFF 
GO

ALTER DATABASE [cs3750] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [cs3750] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [cs3750] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [cs3750] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [cs3750] SET QUERY_STORE = OFF
GO

ALTER DATABASE [cs3750] SET  READ_WRITE 
GO


